export const coffees = [
  {
    id: '1',
    name: 'Expresso Tradicional',
    details: 'O tradicional café feito com água quente e grãos moídos',
    badgeText: ['Tradicional'],
    image: './coffees/coffee1.png',
    price: 9.9,
  },
  {
    id: '2',
    name: 'Expresso Americano',
    details: 'Expresso diluído, menos intenso que o tradicional',
    badgeText: ['Tradicional'],
    image: './coffees/coffee2.png',
    price: 9.9,
  },
  {
    id: '3',
    name: 'Expresso Cremoso',
    details: 'Café expresso tradicional com espuma cremosa',
    badgeText: ['Tradicional'],
    image: './coffees/coffee3.png',
    price: 9.9,
  },
  {
    id: '4',
    name: 'Expresso Gelado',
    details: 'Bebida preparada com café expresso e cubos de gelo',
    badgeText: ['Tradicional', 'gelado'],
    image: './coffees/coffee4.png',
    price: 9.9,
  },
  {
    id: '5',
    name: 'Café com Leite',
    details: 'Meio a meio de expresso tradicional com leite vaporizado',
    badgeText: ['Tradicional', 'com leite'],
    image: './coffees/coffee5.png',
    price: 9.9,
  },
  {
    id: '6',
    name: 'Latte',
    details: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    badgeText: ['Tradicional', 'com leite'],
    image: './coffees/coffee6.png',
    price: 9.9,
  },
  {
    id: '7',
    name: 'Capuccino',
    details: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    badgeText: ['Tradicional', 'com leite'],
    image: './coffees/coffee7.png',
    price: 9.9,
  },
  {
    id: '8',
    name: 'Macchiato',
    details: 'Café expresso misturado com um pouco de leite quente e espuma',
    badgeText: ['Tradicional', 'com leite'],
    image: './coffees/coffee8.png',
    price: 9.9,
  },
  {
    id: '9',
    name: 'Mocaccino',
    details: 'Café expresso com calda de chocolate, pouco leite e espuma',
    badgeText: ['Tradicional', 'com leite'],
    image: './coffees/coffee9.png',
    price: 9.9,
  },
  {
    id: '10',
    name: 'Chocolate Quente',
    details: 'Bebida feita com chocolate dissolvido no leite quente e café',
    badgeText: ['especial', 'com leite'],
    image: './coffees/coffee10.png',
    price: 9.9,
  },
  {
    id: '11',
    name: 'Cubano',
    details: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    badgeText: ['especial', 'alcoólico', 'gelado'],
    image: './coffees/coffee11.png',
    price: 9.9,
  },
  {
    id: '12',
    name: 'Havaiano',
    details: 'Bebida adocicada preparada com café e leite de coco',
    badgeText: ['especial'],
    image: './coffees/coffee12.png',
    price: 9.9,
  },
  {
    id: '13',
    name: 'Árabe',
    details: 'Bebida preparada com grãos de café árabe e especiarias',
    badgeText: ['especial'],
    image: './coffees/coffee13.png',
    price: 9.9,
  },
  {
    id: '14',
    name: 'Irlandês',
    details: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    badgeText: ['especial'],
    image: './coffees/coffee14.png',
    price: 9.9,
  },
]
